### ISSUE TITLE
Description of the output 

### ISSUE THREAD

**Issue by lindenb** [rezwanhosseini/MotifDiff#3]
Hi again,
I got an output in the end, that looks like this:

```
cut -f 1-4  output_nucleotide_type.mono_score_type.NONE_mode_type.max.diff | head | column -s '    ' -o '  ' -t
 	AHR_HUMAN.H11MO.0.B	AIRE_HUMAN.H11MO.0.C	ALX1_HUMAN.H11MO.0.B
.	5.362533           	3.0910416           	3.2999449
.	14.407852          	-1.0498219          	-2.6478348
.	4.267539           	0.81409264          	-0.9886112
.	3.7706938          	-1.0116005          	-1.8009758
.	-11.986725         	-5.2391624          	13.7755785
.	-4.760453          	-0.6144905          	1.0009041
.	3.7736301          	1.5581436           	2.0476913
.	-3.7706938         	0.28768158          	1.2630424
.	3.6350107          	1.1594715           	-0.05406761
```

what is the format of that output ? how can I find the 'best' prediction(s) ?

**Comment by rezwanhosseini** [comment]
the output you're getting shows the log-odd difference for each variant (rows) and each binding site (columns). since you are not using any of the normalization methods (default is NONE, you can add "--method probNorm" to do the normalization) the output only shows the difference between the log-odd of the sequence (containing the variant) for each binding site before and after the variant.

there will be three outputs (plain format separated by .diff, .alt, .ref) showing the scores from the calculations for the sequences with the ref allele (.ref), alt allele (.alt) or the difference between those two (.diff).

if you do the normalization the .alt and .ref outputs will be in the probability range showing the probability of each sequence to be bound to each of those TFs. 
And the .diff output will be in the range (-1,1) showing how much the probability of the sequence to be bound is affected by the variant (1 means the variant is constructive, and -1 means the variant is destructive).

**Comment by lindenb** [comment]
>  for each variant (rows)

ah ok, got it. It would be useful to have this information CHROM:POS:REF:ALT in the first column instead of a dot. Thanks !

**Comment by rezwanhosseini** [comment]
That depends on your vcf file. How ever your variants are named in the vcf file, they will be written the exact same way to the output row names.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lindenb** [comment]
> That depends on your vcf file. How ever your variants are named in the vcf file

ah, ok, got it, the `ID` column in the VCF file is used. All my variants have just a dot in the ID column. `bcftools annotate --set-id` fixed the problem.
